version: '3'

services:
  mongo:
    image: mongo:5.0.8
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - fullcycle

  app:
    build: app/.
    container_name: app
    restart: always
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
      - ./app/frontend:/var/www/html
    ports:
      - 8080:8080
    networks:
      - fullcycle
    depends_on:
      - api

networks:
  fullcycle:
