version: '3'
services:
  mongo:
    image: mongo:5.0.8
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: app/api/.
    container_name: api
    volumes:
      - ./app/api/node.js:/usr/src/app/node.js
    ports:
      - 3000
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    image: nginx:1.20.2
    restart: always
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
      - ./app/frontend:/var/www/html
    ports:
      - 8080:8080
    links:
      - api:apiserver
    depends_on:
      - mongo
      - api
