version: '3'

services:
  mongo:
    image: mongo:5.0.8
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - fullcycle

  api:
    build: api/.
    container_name: api
    restart: always
    ports:
      - 3000:3000
    networks:
      - fullcycle
    depends_on:
      - mongo

  frontend:
    build: frontend/.
    container_name: frontend
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - fullcycle
    depends_on:
      - mongo
      - api

networks:
  fullcycle:
